-- 코드를 입력하세요
# SELECT CAR_ID, round(avg(END_DATE - START_DATE),1) as AVERAGE_DURATION
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE (END_DATE - START_DATE) >= 7
# GROUP BY CAR_ID
# ORDER BY AVERAGE_DURATION desc, CAR_ID desc

SELECT CAR_ID, round(avg(DATEDIFF(END_DATE, START_DATE) + 1),1) as AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION desc, CAR_ID desc